meta_product_name: "Word Warrior"
meta_title: "Word Warrior - helps you learn the words you need to be an academic all-star in English."
meta_description: "Practice vocabulary from the Academic Word List with gap-fill exercises"
meta_image: "logo13_pqprzs.png"                       # should exist in `app/assets/images/`
